### ISSUE TITLE
Their .bashrc is not getting sourced properly on restart

### ISSUE THREAD

**Issue by chendaniely** [dads2busy/sdal_configs#4]
had to manually `. .bashrc` for them to get access to the `rs` alias

**Comment by dads2busy** [comment]
Do they have bash_profile? 
On Jun 2, 2015 10:42 AM, Daniel Chen notifications@github.com wrote:had to manually . .bashrc for them to get access to the rs alias

**Comment by chendaniely** [comment]
Oh. That makes sense. They probably don't
